language: node_js

node_js:
    - "8"

cache:
  directories:
    - "node_modules"

install:
  - 'if [ ! -z $TRAVIS_TAG ]; then sed -i "/version/c\   \"version\" : \"${TRAVIS_TAG}\"," package.json; fi'
  - npm install

before_script:
  - cat package.json
  - npm test

script:
  - npm run build

deploy:
  provider: npm
  email: "mail@jaumesingla.es"
  api_key: "$NPM_TOKEN"
  skip_cleanup: true